config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :members, path: 'manage/auth', controllers: { sessions: "members/sessions" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Root is the forecast submissions form for the month
  root to: 'submit_forecasts#new'

  # submitting forecasts
  # /forecasts
  get '/forecasts', to: 'submit_forecasts#new', as: :new_forecast
  post '/forecasts', to: 'submit_forecasts#create', as: :create_forecast
  # /forecasts/team_name/year/month
  get '/forecasts/(:team_name)/(:year)/(:month)', to: 'submit_forecasts#new', as: :new_team_forecast
  get '/forecast/teams/(:team_name)', to: 'submit_forecasts#index', as: :team_forecasts

  scope :manage do
    resources :teams, param: :team_name
    resources :members, :fields, :holidays, :monthly_forecasts
    scope '/teams/:team_name' do
      get '/forecasts', to: 'forecasts#index'
      get '/forecast/(:year)/(:month)', to: 'forecasts#show', as: :forecast
      put '/forecast/status', to: 'forecast_status#update', as: :forecast_status
      get '/members', to: 'members#team_members', as: :team_members
      post '/forecast/export', to: 'exports#create', as: :export_forecast
      put '/membership', to: 'memberships#update', as: :delete_membership
      resource :fields, controller: :team_fields, as: :team_fields, except: :index
    end
  end

  get '/send_reminder/(:team_name)', to: 'reminders#new', as: :send_reminder
  post '/send_reminder/(:team_name)', to: 'reminders#create', as: :send_reminders

  scope 'admin' do
    get '/', to: 'admins#index', as: :admin_home
  end
end

app/models/field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: fields
#
#  id          :bigint           not null, primary key
#  code        :string
#  default     :boolean          default(FALSE), not null
#  description :text
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_fields_on_code  (code) UNIQUE
#  index_fields_on_name  (name) UNIQUE
#
class Field < ApplicationRecord
  # fields that we probably want to restrict from people deleting
  SPECIAL_FIELDS = [
    'holiday',
    'pto',
    'other'
  ].freeze

  # callbacks
  before_validation :format_fields
  after_commit :add_to_teams

  # associations
  has_many :team_fields, dependent: :destroy
  has_many :teams, through: :team_fields

  # validations
  # name is not case sensitive but code is
  validates :code, uniqueness: true, allow_nil: true
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  private

  # format fields before saving
  #   - strip whitespace
  #   - set empty code to null
  def format_fields
    self.name = name.strip if name.present?
    self.code = nil if !code.present?
  end

  def add_to_teams
    if default
      # TODO: fix this. It will not work if setting default fields for a future month
      team_fields = Team.all.select(:id).map { |team| { team_id: team.id, field_id: id, start_on: Time.zone.today.beginning_of_month}}
      TeamField.create(team_fields)
    end
  end
end

app/controllers/fields_controller.rb
class FieldsController < ManagementController
  before_action -> { requires_at_least_role :representative }
  before_action :set_team_monthly_forecast

  def index
    @fields = Field.all
  end

  def new
    @field = Field.new
  end

  def create
    @field = Field.new(field_params)
    if @field.save
      # if default is selected, it will be added to each foreact automatically
      if @team_monthly_forecast.present? && params[:default] == "0"
        TeamField.create(
          team_id: @team_monthly_forecast.team_id, 
          field_id: @field.id,
          start_on: @team_monthly_forecast.date
        )
      end
      if @team_monthly_forecast
        redirect_to forecast_path( 
          team_name: @team_monthly_forecast.team.slug, 
          year: @team_monthly_forecast.date.year,
          month: @team_monthly_forecast.month_name
        )
      else
        redirect_to @field
      end
    else
      render :new
    end
  end

  def show
    @field = Field.includes(team_fields: :team).find_by(id: params[:id])
    if @field.nil?
      redirect_to action: :index
    end
  end

  def edit
    @field = Field.find_by(id: params[:id])
    if @field
      render :edit
    else
      redirect_to action: :index
    end
  end

  def update
    @field = Field.find_by(id: params[:id])
    if @field&.update(field_params)
      redirect_to(@field)
    else
      render :edit
    end
  end

  def destroy
    @field = Field.find_by(id: params[:id])
    if @field&.destroy
      redirect_to action: :index
    else
      render :show
    end
  end

  private

  def set_team_monthly_forecast
    @team_monthly_forecast = TeamMonthlyForecast.includes(:team).find_by(id: params[:team_monthly_forecast_id])
  end

  def field_params
    params.require(:field).permit(:name, :code, :description, :default)
  end
end

app/views/fields/_form.html.erb
<div class="flex justify-center">
  <div class="min-w-64 w-full sm:w-7/12 md:w-1/2 lg:w-4/12 bg-white px-4 sm:px-8 py-8 mt-8 mb-16 shadow-sm rounded">
    <% if (!defined? form_only)|| (defined? form_only && !form_only) %>
      <% if current_member.is_admin? %>
        <div class="mb-4">
          <%= link_to "Back", :back, class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4" %>
          <%= link_to "All fields", fields_path, class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4" %>
        </div>
      <% end %>
    <% end %>
    <h2 class="text-lg font-bold mb-4"><%= field&.name || "New Field" %></h2>
    <%= form_with model: field, url: path, method: action, id: "field-form" do |form| %>
      <div class="mb-2">
        <%= form.label :name, "Name", class: "text-gray-700" %>
        <%= form.text_field :name, required: true, class: "mt-1 block w-full rounded px-4 py-2 border border-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
      </div>
      <div class="mb-2">
        <%= form.label :code, "Code", class: "text-gray-700" %>
        <%= form.text_field :code, class: "mt-1 block w-full rounded px-4 py-2 border border-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
      </div>
      <div class="mb-2">
        <%= form.label :description, "Description", class: "text-gray-700" %>
        <%= form.text_area :description , class: "mt-1 block w-full rounded px-4 py-2 border border-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
      </div>
      <%# only show default if admin %>
      <% if current_member.is_admin? %>
        <div class="mb-2">
          <%= form.label :default, "Is default field for all teams", class: "text-gray-700" %>
          <%= form.check_box :default, class: "rounded border border-gray-300 text-indigo-600 focus:outline-none focus:border-indigo-300 focus:ring focus:ring-offset-0 focus:ring-indigo-200 focus:ring-opacity-50" %>
        </div>
      <% end %>
      <% if (defined? team) && team.present? %>
        <%= hidden_field_tag :team_id, team.id, id: "team-id", name: "team_id" %>  
      <% end %>
      <%= hidden_field_tag :team_monthly_forecast_id, @team_monthly_forecast&.id, id: "team-monthly-forecast-id", name: "team_monthly_forecast_id" %>  
      <div class="flex justify-end">
        <%= form.submit field.persisted? ? "Save" : "Create", class: "ml-4 cursor-pointer bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-indigo-200" %>
      </div>
    <% end %>
  </div>
</div>

app/views/fields/edit.html.erb
<%= render "form", field: @field, action: :put, path: field_path %>

app/views/fields/index.html.erb
<h2>Fields</h2>
<%= link_to "Add Field", new_field_path%>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Description</th>
      <th>Is default for teams</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if @fields.size > 0 %>
      <% @fields.each do |field| %>
        <tr>
          <td><%= field.name %></td>
          <td><%= field.code || "no code" %></td>
          <td><%= field.description || "no description" %></td>
          <td><%= field.default ? "yes" : "no" %></td>
          <td>       
            <%= link_to 'Show', fields_path(field.id)%>
            <%= link_to 'Edit', edit_field_path(field.id)%>
            <%= link_to 'Delete', url_for(action: :destroy,id: field.id), method: :delete, data: {confirm: "Are you sure you want to delete #{field.name}"} %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan=3>No fields</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/fields/new.html.erb
<%= render "form", field: @field, action: :post, path: fields_path %>

app/views/fields/show.html.erb
<div class="mt-8 mb-4 px-4 sm:px-0">
<div class="mb-4">
<%= link_to "Back", :back, class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4"  %>
<% if current_member.is_admin? %>
<%= link_to "All fields", fields_path, class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4"  %>
<% end %>
</div>
<h2 class="font-bold"><%= @field.name %></h2>
<p class="text-gray-700"><%= @field.code || "No code" %></p>
<p>Is default for teams: <%= @field.default ? "yes" : "no" %></p>
<p><%= @field.description || "No description" %></p>
<%= link_to 'Edit', edit_field_path(@field.id), class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4" %>
<%= link_to 'Delete', url_for(action: :destroy,id: @field.id), method: :delete, data: {confirm: "Are you sure you want to delete #{@field.name}"}, class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4"  %>
<% if current_member.is_admin? %>

<h2>Teams</h2>
<%= link_to "Add to team", class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4"  %>
<table>
  <thead>
    <th>Name</th>
    <th>Actions</th>
  </thead>
  <tbody>
    <% if @field.team_fields.size > 0 %>
      <% @field.team_fields.each do |team_field| %>
        <tr>
          <td><%= team_field.team.name %></td>
          <td>
            <%= link_to 'Show', team_path(team_field.team.slug)%>
            <% if @field.name.downcase != "holiday" %>
              <%= link_to 'Remove from team', url_for(controller: :team_fields, action: :destroy, team_name: team_field.team.slug, id: team_field.id), method: :delete, data: {confirm: "Are you sure you want to remove #{team_field.field.name} from #{team_field.team.name.titleize}"} %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan=4>No teams use this field</td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>