config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :members, path: 'manage/auth', controllers: { sessions: "members/sessions" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Root is the forecast submissions form for the month
  root to: 'submit_forecasts#new'

  # submitting forecasts
  # /forecasts
  get '/forecasts', to: 'submit_forecasts#new', as: :new_forecast
  post '/forecasts', to: 'submit_forecasts#create', as: :create_forecast
  # /forecasts/team_name/year/month
  get '/forecasts/(:team_name)/(:year)/(:month)', to: 'submit_forecasts#new', as: :new_team_forecast
  get '/forecast/teams/(:team_name)', to: 'submit_forecasts#index', as: :team_forecasts

  scope :manage do
    resources :teams, param: :team_name
    resources :members, :fields, :holidays, :monthly_forecasts
    scope '/teams/:team_name' do
      get '/forecasts', to: 'forecasts#index'
      get '/forecast/(:year)/(:month)', to: 'forecasts#show', as: :forecast
      put '/forecast/status', to: 'forecast_status#update', as: :forecast_status
      get '/members', to: 'members#team_members', as: :team_members
      post '/forecast/export', to: 'exports#create', as: :export_forecast
      put '/membership', to: 'memberships#update', as: :delete_membership
      resource :fields, controller: :team_fields, as: :team_fields, except: :index
    end
  end

  get '/send_reminder/(:team_name)', to: 'reminders#new', as: :send_reminder
  post '/send_reminder/(:team_name)', to: 'reminders#create', as: :send_reminders

  scope 'admin' do
    get '/', to: 'admins#index', as: :admin_home
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forecasts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-100">
    <nav class="flex bg-white py-2 sm:py-4 px-2 sm:px-6 lg:px-8 w-full shadow-sm">
      <div class="flex-1">
        <h2 class="font-bold text-2xl">
          <%= link_to "Forecasts", root_path, method: :get %>
        </h2>
      </div>
      <div class="flex-1 flex justify-end">
        <% if member_signed_in? %>
          <div class="flex space-x-4">
          <%= link_to "Home", home_path, class: "hover:text-gray-500" %>
          <% if current_member.team_id.present? %>          
            <%= link_to "Current Forecast", forecast_path(current_member.team.slug), class: "hover:text-gray-500" %>
          <% end %>
          <%= link_to "Logout", destroy_member_session_path, method: :delete, class: "hover:text-gray-500" %>
          </div>
        <% else %>
          <div class="flex space-x-4">
          <%= link_to "Forecasts", team_forecasts_path, class: "hover:text-gray-500" %>
          <%= link_to "Login", new_member_session_path, class: "hover:text-gray-500" %>
          </div>
        <% end %>
      </div>
    </nav>
    <% if !devise_controller? %>
      <div class="flex justify-end">
        <% if notice.present? %>
          <div class="mr-8 notice bg-indigo-100 border border-indigo-400 text-indigo-700 my-4 px-4 py-3 rounded relative">
            <%= notice %>
          </div> 
        <% end %>
        <% if alert.present? %>
          <div class="alert m-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative"><%= alert %></div>
        <% end %>
      </div>
    <% end %>
    <div class="px-0 sm:px-4 md:px-6 lg:px-8">
      <%= yield %>
    </div>
    <%= render "shared/modal" %>
  </body>
</html>