config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :members, path: 'manage/auth', controllers: { sessions: "members/sessions" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Root is the forecast submissions form for the month
  root to: 'submit_forecasts#new'

  # submitting forecasts
  # /forecasts
  get '/forecasts', to: 'submit_forecasts#new', as: :new_forecast
  post '/forecasts', to: 'submit_forecasts#create', as: :create_forecast
  # /forecasts/team_name/year/month
  get '/forecasts/(:team_name)/(:year)/(:month)', to: 'submit_forecasts#new', as: :new_team_forecast
  get '/forecast/teams/(:team_name)', to: 'submit_forecasts#index', as: :team_forecasts

  scope :manage do
    resources :teams, param: :team_name
    resources :members, :fields, :holidays, :monthly_forecasts
    scope '/teams/:team_name' do
      get '/forecasts', to: 'forecasts#index'
      get '/forecast/(:year)/(:month)', to: 'forecasts#show', as: :forecast
      put '/forecast/status', to: 'forecast_status#update', as: :forecast_status
      get '/members', to: 'members#team_members', as: :team_members
      post '/forecast/export', to: 'exports#create', as: :export_forecast
      put '/membership', to: 'memberships#update', as: :delete_membership
      resource :fields, controller: :team_fields, as: :team_fields, except: :index
    end
  end

  get '/send_reminder/(:team_name)', to: 'reminders#new', as: :send_reminder
  post '/send_reminder/(:team_name)', to: 'reminders#create', as: :send_reminders

  scope 'admin' do
    get '/', to: 'admins#index', as: :admin_home
  end
end

app/models/member.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: members
#
#  id                     :bigint           not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  email                  :string           not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  middle_name            :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role_id                :bigint
#  team_id                :bigint
#
# Indexes
#
#  index_members_on_confirmation_token                        (confirmation_token) UNIQUE
#  index_members_on_email                                     (email) UNIQUE
#  index_members_on_last_name_and_middle_name_and_first_name  (last_name,middle_name,first_name) UNIQUE
#  index_members_on_reset_password_token                      (reset_password_token) UNIQUE
#  index_members_on_role_id                                   (role_id)
#  index_members_on_team_id                                   (team_id)
#
# Foreign Keys
#
#  fk_rails_...  (role_id => roles.id)
#  fk_rails_...  (team_id => teams.id)
#
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable,
         :timeoutable
         # :confirmable
         # :registerable
  has_paper_trail skip: [
    :encrypted_password,
    :reset_password_token,
    :reset_password_sent_at,
    :remember_created_at,
    :confirmation_token,
    :confirmed_at,
    :confirmation_sent_at,
    :unconfirmed_email
  ], versions: {
    class_name: 'MemberVersion'
  }

  # callbacks
  # format all fields before saving
  before_validation :format_fields

  # send set password email if new user has a role or changed from nothing to something
  after_create :send_reset_password_instructions, if: proc { role.present? }

  # associations
  belongs_to :team, optional: true
  belongs_to :role, optional: true
  has_many :member_forecasts, dependent: :destroy

  # validations
  validates :email, presence: true, uniqueness: {
    case_sensitive: false
  }
  validates :first_name, uniqueness: {
    scope: %i[middle_name last_name],
    case_sensitive: false
  }, allow_blank: true

  # display full name
  def full_name
    # remove repeat whitespace and display full name
    "#{first_name} #{middle_name} #{last_name}".squeeze(' ').strip
  end

  # member roles
  # role hierarchy: admin > manager > representative
  def at_least_a_manager?
    case role&.name&.downcase
    when 'admin', 'manager'
      true
    else
      false
    end
  end

  def at_least_a_representative?
    case role&.name&.downcase
    when 'admin', 'manager', 'representative'
      true
    else
      false
    end
  end

  # verifies member is at least the provided team name
  def at_least_a?(role_name)
    at_least_role_name = role_name.to_s.downcase
    case at_least_role_name
    when 'admin'
      is_admin?
    when 'manager'
      at_least_a_manager?
    when 'representative'
      at_least_a_representative?
    end
  end

  def is_admin?
    role&.name&.downcase == 'admin'
  end

  def is_manager?
    role&.name&.downcase == 'manager'
  end

  def is_representative?
    role&.name&.downcase == 'representative'
  end

  private

  # password isnt required for new records
  def password_required?
    return false if new_record?
    super
  end

  # format all fields before saving
  #   - strip extra whitespace
  #   - downcase
  def format_fields
    # downcase email, first name, middle name, and last name
    %i[email first_name middle_name last_name].each do |attribute|
      send("#{attribute}=", send(attribute).strip.downcase) if send(attribute).present?
    end
  end
end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
  before_action :find_user, only: :create
  # user cannot sign in if they dont have a role

  private

  def find_user
    member = Member.includes(:role).find_by(email: params[:member][:email])
    if member && member&.role.nil?
      set_flash_message! :alert, :not_permitted
      redirect_to action: :new
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ManagementController
  before_action -> { requires_at_least_role :representative, team_name_slug: params[:team_name] }, except: [:index]
  before_action -> { requires_at_least_role :admin }, only: [:index]
  before_action :set_teams, :set_roles, except: [:index]

  def index
    @members = Member.includes(:team, :role).all
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to @member
    else
      render :new
    end
  end

  def show
    @member = Member.includes(:team, :role).find_by(id: params[:id])
    if @member.nil?
      redirect_to action: :index
    end
  end

  def edit
    @member = Member.includes(:team, :role).find_by(id: params[:id])
    if @member
      render :edit
    else
      redirect_to action: :index
    end
  end

  def update
    @member = Member.includes(:team, :role).find_by(id: params[:id])
    if @member&.update(member_params)
      redirect_to(@member)
    else
      redirect_to action: :edit
    end
  end

  def destroy
    @member = Member.find_by(id: params[:id])
    if @member&.destroy
      redirect_to action: :index
    else
      render :show
    end
  end

  private

  def member_params
    params.require(:member).permit(:first_name, :middle_name, :last_name, :email, :team_id, :role_id)
  end

  def set_teams
    @teams = Team.all
    if params[:team_id].present?
      id = params[:team_id].to_i 
      @team = @teams.detect { |team| team.id == id }
    end
  end

  def set_roles
    @roles = Role.all
  end
end

app/views/members/_form.html.erb
<div class="flex justify-center">
  <div class="min-w-64 w-full sm:w-7/12 md:w-1/2 lg:w-4/12 bg-white px-4 sm:px-8 py-8 mt-8 mb-16 shadow-sm rounded">
    <div class="mb-4">
    <%= link_to "Back", :back, class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4" %>
    <% if current_member.is_admin? %>
      <%= link_to "All Members", members_path, class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4" %>
    <% end %>
    </div>
    <h2 class="text-lg font-bold"><%= member&.new_record? ? "New Member" : member.full_name %></h2>
    <% if (defined? team) && team.present? %>
      <p class="text-gray-700 mb-4">Add member to <%= team.name %> team</p>
    <% end %>
    <%= form_with model: member, url: path, method: action, id: "member-form" do |form| %>
      <div class="mb-4">
        <%= form.label :first_name, "First Name", class: "text-gray-700" %>
        <%= form.text_field :first_name, required: true, class: "mt-1 block w-full rounded px-4 py-2 border border-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
      </div>
      <div class="mb-4">
        <%= form.label :middle_name, "Middle Name", class: "text-gray-700"  %>
        <%= form.text_field :middle_name, class: "mt-1 block w-full rounded px-4 py-2 border border-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
      </div>
      <div class="mb-4">
        <%= form.label :last_name, "Last Name", class: "text-gray-700"  %>
        <%= form.text_field :last_name, required: true, class: "mt-1 block w-full rounded px-4 py-2 border border-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
      </div>
      <div class="mb-4">
        <%= form.label :email, "Email", class: "text-gray-700"  %>
        <%= form.text_field :email, required: true, class: "mt-1 block w-full rounded px-4 py-2 border border-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
      </div>
      <% if (defined? team) && team.present? %>
        <%= form.hidden_field :team_id, name: "member[team_id]", value: team&.id %>
      <% else %>
        <div class="mb-4">
          <%= form.label :team_id, "Team", class: "text-gray-700"  %>
          <div class="relative inline-block w-full mt-4">
            <%= form.select :team_id, options_for_select(@teams&.map { |tm| [tm.name.titleize, tm.id] } + [["no team", '']], member.team_id), prompt: "select team", name: "team_id", id: "team-id", class: "appearance-none block w-full rounded px-4 py-2 border border-gray-300 focus:outline-none focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
            <div class="absolute inset-y-0 right-0 flex items-center px-2 pointer-events-none">
              <svg class="w-4 h-4 fill-current" viewBox="0 0 20 20"><path d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" fill-rule="evenodd"></path></svg>
            </div>
          </div>
        </div>
      <% end %>
      <div class="mb-4">
        <p class="text-sm text-gray-700 mb-4">Optionally provide a role for a user. Only users with roles can login</p>
        <p class="text-sm text-gray-700mb-4">Role Descriptions</p>
        <ul class="text-sm text-gray-700 pb-4">
          <li class="mb-2"><span class="font-bold">Admin:</span> manage entire application. Can manage and view forecasts for all teams.</li>
          <li class="mb-2"><span class="font-bold">Manager:</span> Can only manage and view forecasts for the team that the member belongs to.</li>
          <li class="mb-2"><span class="font-bold">Representative:</span> Can only manage the team that the member belongs to. Cannot see any forecasts.</li>
        </ul>
        <div>
          <%= form.label :role_id, "Role", class: "text-gray-700"  %>
          <div class="relative inline-block w-full">
            <%= form.select :role_id, options_for_select(@roles&.map { |role| [role.name.downcase, role.id] } + [["no role", '']], member.role_id), prompt: "select role", name: "role_id", id: "role-id", class: "block appearance-none w-full rounded px-4 py-2 focus:outline-none border border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
            <div class="absolute inset-y-0 right-0 flex items-center px-2 pointer-events-none">
              <svg class="w-4 h-4 fill-current" viewBox="0 0 20 20"><path d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" fill-rule="evenodd"></path></svg>
            </div>
          </div>
        </div>
      </div>
      <div class="flex justify-end">
        <%= form.submit member.persisted? ? "Save" : "Create", class: "cursor-pointer bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-indigo-200" %>
      </div>    
    <% end %>
  </div>
</div>

app/views/members/edit.html.erb
<%= render "form", member: @member, action: :put, path: member_path %>

app/views/members/index.html.erb
<h2>Members</h2>
<%= link_to "Add Member", new_member_path%>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Team</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% if @members.size > 0 %>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %></td>
        <td><%= member.email %></td>
        <td><%= member.role&.name %></td>
        <% if member.team_id %>
          <td><%= link_to member.team.name.titleize, team_path(member.team.slug) %></td>
        <% else %>
          <td>No team</td>
        <% end %>
        <td>
          <%= link_to 'Show', members_path(member.id)%>
          <%= link_to 'Edit', edit_member_path(member.id)%>
          <%= link_to 'Delete', url_for(action: :destroy,id: member.id), method: :delete, data: {confirm: "Are you sure you want to delete #{member.full_name}"} %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan=5>No members</td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/members/new.html.erb
<%= render "form", member: @member, action: :post, path: members_path, team: @team %>

app/views/members/show.html.erb
<div class="mt-8 mb-4 px-4 sm:px-0">
<div class="mb-4">
<%= link_to "Back", :back, class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4" %>
<% if current_member.is_admin? %>
  <%= link_to "All Members", members_path, class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4" %>
<% end %>
</div>
<h2 class="font-bold"><%= @member.full_name %></h2>
<p class="text-gray-700"><%= @member.email %></p>
<% if @member.role %>
  <p class="text-gray-700">Role: <%= @member.role.name %>
<% end %>
<% if @member.team_id%>
  <p><%= link_to @member.team.name.titleize, team_path(@member.team.slug), class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4"  %></p>
<% else %>
  <p><%= @member.full_name %> does not belong to a team</p>
<% end %>
<div class="my-4">
<%= link_to 'Edit', edit_member_path(@member.id), class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4" %>
<%= link_to 'Delete', url_for(action: :destroy,id: @member.id), method: :delete, data: {confirm: "Are you sure you want to delete #{@member.full_name}"}, class: "cursor-pointer text-indigo-500 no-underline hover:underline mr-4"  %>
</div>
</div>